# Site settings
title: helloplease
email: hi@helloplease.me
description: > # this means to ignore newlines until "baseurl:"
  Chicago-based design, web design, design students, graphic design.

twitter_username: hellopleaseme
github_username:  jekyll

# Build settings
markdown: kramdown
